name: Testing and validation

on: [push, pull_request]

jobs:
  tests:
    name: Tests with node ${{ matrix.node }}
    strategy:
      matrix:
        node: [ 16.x ]
    uses: Bernardo-MG/github-workflow-angular/.github/workflows/testing.yml@v1
    with:
      node: ${{ matrix.node }}
